services:
    postgresql:
        image: postgres:17.5
        restart: always
        ports:
            - 5432:5432
        env_file:
            - ./.env
        volumes:
            - pg_data:/var/lib/postgresql/data

    n8n:
        image: docker.n8n.io/n8nio/n8n:1.85.4
        restart: always
        ports:
            - 5678:5678
        env_file:
            - ./.env
        volumes:
            - n8n_data:/home/node/.n8n
            - ./dist:/home/node/.n8n/custom
        links:
            - postgresql
        depends_on:
            - postgresql

volumes:
    pg_data:
    n8n_data:
